In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import plotly.express as px
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv('cardekho_imputated.csv')

In [4]:
df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15411 non-null  int64
 1   car_name           15411 non-null  object
 2   brand              15411 non-null  object
 3   model              15411 non-null  object
 4   vehicle_age        15411 non-null  int64
 5   km_driven          15411 non-null  int64
 6   seller_type        15411 non-null  object
 7   fuel_type          15411 non-null  object
 8   transmission_type  15411 non-null  object
 9   mileage            15411 non-null  float64
 10  engine             15411 non-null  int64
 11  max_power          15411 non-null  float64
 12  seats              15411 non-null  int64
 13  selling_price      15411 non-null  int64
dtypes: float64(2), int64(6), object(6)
memory usage: 1.6+ MB

In [6]:
df.isnull().sum()

Unnamed: 0           0
car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [7]:
df.drop('car_name',axis=1,inplace=True)

In [8]:
df.drop('brand',axis=1,inplace=True)

In [9]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [10]:
num_features= [f for f in df.columns if df[f].dtype!='O']
cat_features= [f for f in df.columns if df[f].dtype=='O']
dis_features= [f for f in num_features if len(df[f].unique())<=25]
cont_features= [f for f in df.columns if len(df[f].unique())>25]

print('No of num_fea:',len(num_features))
print('No of cat_fea:',len(cat_features))
print('No of dis_fea:',len(dis_features))
print('No of cont_fea:',len(cont_features))

No of num_fea: 8
No of cat_fea: 4
No of dis_fea: 2
No of cont_fea: 7

In [11]:
from sklearn.model_selection import train_test_split
X=df.drop(['selling_price'],axis=1)
y=df['selling_price']

In [12]:
X.drop('Unnamed: 0',axis=1,inplace=True)

In [13]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [14]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X['model']=le.fit_transform(X['model'])

In [15]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [16]:
num_features=X.select_dtypes(exclude="object").columns
onehot_feature=['seller_type','fuel_type','transmission_type']

In [17]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer=StandardScaler()
oh_transformer=OneHotEncoder(drop='first')

preprocessor=ColumnTransformer(
    [
        ("OneHot Encoder",oh_transformer,onehot_feature),
        ("StandardScaler",numeric_transformer,num_features)
    ],remainder='passthrough'
)

In [18]:
pd.DataFrame(X)

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5
...,...,...,...,...,...,...,...,...,...,...
15406,117,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5
15407,42,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7
15408,77,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5
15409,114,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7
15410,25,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5

In [20]:
X=preprocessor.fit_transform(X)

In [21]:
X

array([[ 1.        ,  0.        ,  0.        , ..., -1.32425883,
        -1.26335238, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.55471774,
        -0.43257082, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.55471774,
        -0.47911321, -0.40302241],
       ...,
       [ 0.        ,  0.        ,  1.        , ...,  0.02291783,
         0.06822523, -0.40302241],
       [ 0.        ,  0.        ,  1.        , ...,  1.32979434,
         0.91715831,  2.07344426],
       [ 0.        ,  0.        ,  0.        , ...,  0.02099878,
         0.39588361, -0.40302241]], shape=(15411, 14))

In [25]:
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.2,random_state=42)

In [22]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error,root_mean_squared_error

In [23]:
def evaluate_model(true,predicted):
    mae=mean_absolute_error(true,predicted)
    mse=mean_squared_error(true,predicted)
    rmse=root_mean_squared_error(true,predicted)
    r2_sc=r2_score(true,predicted)
    return mae,mse,rmse,r2_sc

In [24]:
models={
    "LinearRegression":LinearRegression(),
    "Lasso": Lasso(),
    "Ridge":Ridge(),
    "KNeighborsRegressor":KNeighborsRegressor(),
    "DecisionTreeRegressor":DecisionTreeRegressor(),
    "RandomForestRegressor":RandomForestRegressor()
}

In [28]:
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)

    y_train_pred=model.predict(X_train)
    y_test_pred=model.predict(X_test)

    model_train_mae,model_train_mse,model_train_rmse,model_train_r2_sc=evaluate_model(y_train,y_train_pred)
    model_test_mae,model_test_mse,model_test_rmse,model_test_r2_sc=evaluate_model(y_test,y_test_pred)

    print(list(models.keys())[i])

    print("Model train Performance")
    print('mean_absolute_error:{:.4f}'.format(model_train_mae))
    print('mean_square_error:{:.4f}'.format(model_train_mse))
    print('root_mean_square_error:{:.4f}'.format(model_train_rmse))
    print('r2_score:{:.4f}'.format(model_train_r2_sc))
    print("---")
    print("Model test Performance")
    print('mean_absolute_error:{:.4f}'.format(model_test_mae))
    print('mean_square_error:{:.4f}'.format(model_test_mse))
    print('root_mean_square_error:{:.4f}'.format(model_test_rmse))
    print('r2_score:{:.4f}'.format(model_test_r2_sc))

    print("="*32)
    print(" ")

LinearRegression
Model train Performance
mean_absolute_error:268101.6071
mean_square_error:306756099359.7596
root_mean_square_error:553855.6665
r2_score:0.6218
---
Model test Performance
mean_absolute_error:279618.5794
mean_square_error:252550062888.5655
root_mean_square_error:502543.5930
r2_score:0.6645
================================

Lasso
Model train Performance
mean_absolute_error:268099.2226
mean_square_error:306756104248.3742
root_mean_square_error:553855.6710
r2_score:0.6218
---
Model test Performance
mean_absolute_error:279614.7461
mean_square_error:252549134806.7813
root_mean_square_error:502542.6696
r2_score:0.6645
================================

Ridge
Model train Performance
mean_absolute_error:268059.8015
mean_square_error:306756818740.9266
root_mean_square_error:553856.3160
r2_score:0.6218
---
Model test Performance
mean_absolute_error:279557.2169
mean_square_error:252540243247.9685
root_mean_square_error:502533.8230
r2_score:0.6645
================================

KNeighborsRegressor
Model train Performance
mean_absolute_error:91425.6327
mean_square_error:106193229526.2816
root_mean_square_error:325873.0267
r2_score:0.8691
---
Model test Performance
mean_absolute_error:112526.3461
mean_square_error:64021344520.1508
root_mean_square_error:253024.3951
r2_score:0.9150
================================

DecisionTreeRegressor
Model train Performance
mean_absolute_error:5164.8199
mean_square_error:432524990.5364
root_mean_square_error:20797.2352
r2_score:0.9995
---
Model test Performance
mean_absolute_error:123904.9816
mean_square_error:91296387887.6320
root_mean_square_error:302152.9214
r2_score:0.8787
================================

RandomForestRegressor
Model train Performance
mean_absolute_error:39329.9717
mean_square_error:15346792002.4724
root_mean_square_error:123882.1698
r2_score:0.9811
---
Model test Performance
mean_absolute_error:102176.0714
mean_square_error:52064547523.0572
root_mean_square_error:228176.5709
r2_score:0.9308
================================

In [29]:
#Hyperparameter tuning

knn_params={"n_neighbors":[2,3,10,20,40,50]}
rf_params={
    "max_depth":[5,8,15,None,10],
    "max_features":[5,7,"auto",8],
    "min_samples_split":[2,8,15,20],
    "n_estimators":[100,200,500,1000]
}

In [30]:
randomcv_models=[
    ('KNN',KNeighborsRegressor(),knn_params),
    ("RF",RandomForestRegressor(),rf_params)
]

In [31]:
from sklearn.model_selection import RandomizedSearchCV
model_params={}
for name,model,params in randomcv_models:
    random=RandomizedSearchCV(
        estimator=model,
        param_distributions=params,
        n_iter=100,
        cv=3,
        verbose=2,
        n_jobs=1
    )
    random.fit(X_train,y_train)
    model_params[name]=random.best_params_
for modelname in model_params:
    print("{modelname}:",model_params[modelname])

Fitting 3 folds for each of 6 candidates, totalling 18 fits
[CV] END ......................................n_neighbors=2; total time=   0.3s
[CV] END ......................................n_neighbors=2; total time=   0.3s
[CV] END ......................................n_neighbors=2; total time=   0.3s
[CV] END ......................................n_neighbors=3; total time=   0.3s
[CV] END ......................................n_neighbors=3; total time=   0.3s
[CV] END ......................................n_neighbors=3; total time=   0.4s
[CV] END .....................................n_neighbors=10; total time=   0.5s
[CV] END .....................................n_neighbors=10; total time=   0.6s
[CV] END .....................................n_neighbors=10; total time=   0.6s
[CV] END .....................................n_neighbors=20; total time=   0.7s
[CV] END .....................................n_neighbors=20; total time=   0.7s
[CV] END .....................................n_neighbors=20; total time=   0.7s
[CV] END .....................................n_neighbors=40; total time=   0.9s
[CV] END .....................................n_neighbors=40; total time=   0.9s
[CV] END .....................................n_neighbors=40; total time=   0.9s
[CV] END .....................................n_neighbors=50; total time=   1.0s
[CV] END .....................................n_neighbors=50; total time=   1.0s
[CV] END .....................................n_neighbors=50; total time=   1.0s
Fitting 3 folds for each of 100 candidates, totalling 300 fits
[CV] END max_depth=None, max_features=auto, min_samples_split=20, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=20, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=20, n_estimators=200; total time=   0.0s
[CV] END max_depth=10, max_features=8, min_samples_split=2, n_estimators=500; total time=   4.9s
[CV] END max_depth=10, max_features=8, min_samples_split=2, n_estimators=500; total time=   5.1s
[CV] END max_depth=10, max_features=8, min_samples_split=2, n_estimators=500; total time=   5.2s
[CV] END max_depth=8, max_features=5, min_samples_split=20, n_estimators=100; total time=   0.5s
[CV] END max_depth=8, max_features=5, min_samples_split=20, n_estimators=100; total time=   0.5s
[CV] END max_depth=8, max_features=5, min_samples_split=20, n_estimators=100; total time=   0.5s
[CV] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=500; total time=   0.0s
[CV] END max_depth=15, max_features=5, min_samples_split=8, n_estimators=200; total time=   1.8s
[CV] END max_depth=15, max_features=5, min_samples_split=8, n_estimators=200; total time=   1.8s
[CV] END max_depth=15, max_features=5, min_samples_split=8, n_estimators=200; total time=   1.8s
[CV] END max_depth=15, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=5, max_features=8, min_samples_split=20, n_estimators=1000; total time=   6.8s
[CV] END max_depth=5, max_features=8, min_samples_split=20, n_estimators=1000; total time=   9.1s
[CV] END max_depth=5, max_features=8, min_samples_split=20, n_estimators=1000; total time=   9.0s
[CV] END max_depth=10, max_features=8, min_samples_split=8, n_estimators=100; total time=   1.4s
[CV] END max_depth=10, max_features=8, min_samples_split=8, n_estimators=100; total time=   1.5s
[CV] END max_depth=10, max_features=8, min_samples_split=8, n_estimators=100; total time=   1.4s
[CV] END max_depth=None, max_features=8, min_samples_split=8, n_estimators=1000; total time=  22.4s
[CV] END max_depth=None, max_features=8, min_samples_split=8, n_estimators=1000; total time=  21.9s
[CV] END max_depth=None, max_features=8, min_samples_split=8, n_estimators=1000; total time=  22.1s
[CV] END max_depth=8, max_features=5, min_samples_split=15, n_estimators=200; total time=   1.8s
[CV] END max_depth=8, max_features=5, min_samples_split=15, n_estimators=200; total time=   1.7s
[CV] END max_depth=8, max_features=5, min_samples_split=15, n_estimators=200; total time=   1.8s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=200; total time=   2.5s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=200; total time=   2.5s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=200; total time=   2.6s
[CV] END max_depth=None, max_features=7, min_samples_split=8, n_estimators=500; total time=  10.0s
[CV] END max_depth=None, max_features=7, min_samples_split=8, n_estimators=500; total time=   9.8s
[CV] END max_depth=None, max_features=7, min_samples_split=8, n_estimators=500; total time=  10.0s
[CV] END max_depth=None, max_features=8, min_samples_split=15, n_estimators=100; total time=   1.8s
[CV] END max_depth=None, max_features=8, min_samples_split=15, n_estimators=100; total time=   1.8s
[CV] END max_depth=None, max_features=8, min_samples_split=15, n_estimators=100; total time=   1.9s
[CV] END max_depth=15, max_features=5, min_samples_split=20, n_estimators=500; total time=   6.4s
[CV] END max_depth=15, max_features=5, min_samples_split=20, n_estimators=500; total time=   6.4s
[CV] END max_depth=15, max_features=5, min_samples_split=20, n_estimators=500; total time=   6.3s
[CV] END max_depth=8, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=100; total time=   0.7s
[CV] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=100; total time=   0.7s
[CV] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=100; total time=   0.8s
[CV] END max_depth=10, max_features=8, min_samples_split=8, n_estimators=500; total time=   7.6s
[CV] END max_depth=10, max_features=8, min_samples_split=8, n_estimators=500; total time=   7.7s
[CV] END max_depth=10, max_features=8, min_samples_split=8, n_estimators=500; total time=   7.7s
[CV] END max_depth=8, max_features=7, min_samples_split=2, n_estimators=200; total time=   2.3s
[CV] END max_depth=8, max_features=7, min_samples_split=2, n_estimators=200; total time=   2.3s
[CV] END max_depth=8, max_features=7, min_samples_split=2, n_estimators=200; total time=   2.3s
[CV] END max_depth=None, max_features=5, min_samples_split=2, n_estimators=500; total time=  12.1s
[CV] END max_depth=None, max_features=5, min_samples_split=2, n_estimators=500; total time=  12.1s
[CV] END max_depth=None, max_features=5, min_samples_split=2, n_estimators=500; total time=  12.0s
[CV] END max_depth=15, max_features=7, min_samples_split=20, n_estimators=100; total time=   1.5s
[CV] END max_depth=15, max_features=7, min_samples_split=20, n_estimators=100; total time=   1.5s
[CV] END max_depth=15, max_features=7, min_samples_split=20, n_estimators=100; total time=   1.7s
[CV] END max_depth=15, max_features=7, min_samples_split=8, n_estimators=200; total time=   3.7s
[CV] END max_depth=15, max_features=7, min_samples_split=8, n_estimators=200; total time=   3.5s
[CV] END max_depth=15, max_features=7, min_samples_split=8, n_estimators=200; total time=   3.6s
[CV] END max_depth=15, max_features=8, min_samples_split=15, n_estimators=500; total time=   9.5s
[CV] END max_depth=15, max_features=8, min_samples_split=15, n_estimators=500; total time=   9.4s
[CV] END max_depth=15, max_features=8, min_samples_split=15, n_estimators=500; total time=   9.6s
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=200; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=200; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=200; total time=   0.0s
[CV] END max_depth=8, max_features=8, min_samples_split=15, n_estimators=1000; total time=  11.5s
[CV] END max_depth=8, max_features=8, min_samples_split=15, n_estimators=1000; total time=  13.0s
[CV] END max_depth=8, max_features=8, min_samples_split=15, n_estimators=1000; total time=  13.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=8, n_estimators=1000; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=8, n_estimators=1000; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=8, n_estimators=1000; total time=   0.0s
[CV] END max_depth=None, max_features=7, min_samples_split=2, n_estimators=200; total time=   5.9s
[CV] END max_depth=None, max_features=7, min_samples_split=2, n_estimators=200; total time=   5.8s
[CV] END max_depth=None, max_features=7, min_samples_split=2, n_estimators=200; total time=   5.9s
[CV] END max_depth=8, max_features=5, min_samples_split=2, n_estimators=1000; total time=   9.5s
[CV] END max_depth=8, max_features=5, min_samples_split=2, n_estimators=1000; total time=   9.5s
[CV] END max_depth=8, max_features=5, min_samples_split=2, n_estimators=1000; total time=   9.6s
[CV] END max_depth=5, max_features=7, min_samples_split=8, n_estimators=500; total time=   4.4s
[CV] END max_depth=5, max_features=7, min_samples_split=8, n_estimators=500; total time=   4.2s
[CV] END max_depth=5, max_features=7, min_samples_split=8, n_estimators=500; total time=   4.1s
[CV] END max_depth=5, max_features=8, min_samples_split=2, n_estimators=500; total time=   4.6s
[CV] END max_depth=5, max_features=8, min_samples_split=2, n_estimators=500; total time=   4.7s
[CV] END max_depth=5, max_features=8, min_samples_split=2, n_estimators=500; total time=   4.9s
[CV] END max_depth=None, max_features=5, min_samples_split=20, n_estimators=1000; total time=  14.0s
[CV] END max_depth=None, max_features=5, min_samples_split=20, n_estimators=1000; total time=  14.2s
[CV] END max_depth=None, max_features=5, min_samples_split=20, n_estimators=1000; total time=  14.2s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=100; total time=   1.8s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=100; total time=   1.8s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=100; total time=   1.8s
[CV] END max_depth=8, max_features=8, min_samples_split=20, n_estimators=500; total time=   6.6s
[CV] END max_depth=8, max_features=8, min_samples_split=20, n_estimators=500; total time=   6.3s
[CV] END max_depth=8, max_features=8, min_samples_split=20, n_estimators=500; total time=   6.0s
[CV] END max_depth=None, max_features=7, min_samples_split=2, n_estimators=500; total time=  13.2s
[CV] END max_depth=None, max_features=7, min_samples_split=2, n_estimators=500; total time=  14.5s
[CV] END max_depth=None, max_features=7, min_samples_split=2, n_estimators=500; total time=  14.4s
[CV] END max_depth=10, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END max_depth=15, max_features=7, min_samples_split=2, n_estimators=1000; total time=  22.7s
[CV] END max_depth=15, max_features=7, min_samples_split=2, n_estimators=1000; total time=  22.8s
[CV] END max_depth=15, max_features=7, min_samples_split=2, n_estimators=1000; total time=  22.3s
[CV] END max_depth=10, max_features=8, min_samples_split=2, n_estimators=1000; total time=  16.0s
[CV] END max_depth=10, max_features=8, min_samples_split=2, n_estimators=1000; total time=  16.3s
[CV] END max_depth=10, max_features=8, min_samples_split=2, n_estimators=1000; total time=  16.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END max_depth=8, max_features=8, min_samples_split=8, n_estimators=200; total time=   2.5s
[CV] END max_depth=8, max_features=8, min_samples_split=8, n_estimators=200; total time=   2.6s
[CV] END max_depth=8, max_features=8, min_samples_split=8, n_estimators=200; total time=   2.5s
[CV] END max_depth=8, max_features=8, min_samples_split=2, n_estimators=100; total time=   1.2s
[CV] END max_depth=8, max_features=8, min_samples_split=2, n_estimators=100; total time=   1.2s
[CV] END max_depth=8, max_features=8, min_samples_split=2, n_estimators=100; total time=   1.2s
[CV] END max_depth=None, max_features=7, min_samples_split=20, n_estimators=500; total time=   8.3s
[CV] END max_depth=None, max_features=7, min_samples_split=20, n_estimators=500; total time=   8.2s
[CV] END max_depth=None, max_features=7, min_samples_split=20, n_estimators=500; total time=   8.7s
[CV] END max_depth=None, max_features=8, min_samples_split=2, n_estimators=200; total time=   6.5s
[CV] END max_depth=None, max_features=8, min_samples_split=2, n_estimators=200; total time=   6.5s
[CV] END max_depth=None, max_features=8, min_samples_split=2, n_estimators=200; total time=   6.1s
[CV] END max_depth=10, max_features=5, min_samples_split=20, n_estimators=200; total time=   2.1s
[CV] END max_depth=10, max_features=5, min_samples_split=20, n_estimators=200; total time=   2.1s
[CV] END max_depth=10, max_features=5, min_samples_split=20, n_estimators=200; total time=   2.1s
[CV] END max_depth=10, max_features=5, min_samples_split=8, n_estimators=100; total time=   1.0s
[CV] END max_depth=10, max_features=5, min_samples_split=8, n_estimators=100; total time=   1.0s
[CV] END max_depth=10, max_features=5, min_samples_split=8, n_estimators=100; total time=   1.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=8, n_estimators=1000; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=8, n_estimators=1000; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=8, n_estimators=1000; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=20, n_estimators=1000; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=20, n_estimators=1000; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=20, n_estimators=1000; total time=   0.0s
[CV] END max_depth=5, max_features=7, min_samples_split=8, n_estimators=100; total time=   0.7s
[CV] END max_depth=5, max_features=7, min_samples_split=8, n_estimators=100; total time=   0.7s
[CV] END max_depth=5, max_features=7, min_samples_split=8, n_estimators=100; total time=   0.7s
[CV] END max_depth=15, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=8, max_features=5, min_samples_split=8, n_estimators=500; total time=   4.4s
[CV] END max_depth=8, max_features=5, min_samples_split=8, n_estimators=500; total time=   4.5s
[CV] END max_depth=8, max_features=5, min_samples_split=8, n_estimators=500; total time=   4.6s
[CV] END max_depth=8, max_features=7, min_samples_split=15, n_estimators=100; total time=   1.2s
[CV] END max_depth=8, max_features=7, min_samples_split=15, n_estimators=100; total time=   1.1s
[CV] END max_depth=8, max_features=7, min_samples_split=15, n_estimators=100; total time=   1.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=200; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=200; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=8, min_samples_split=20, n_estimators=1000; total time=  18.6s
[CV] END max_depth=None, max_features=8, min_samples_split=20, n_estimators=1000; total time=  18.1s
[CV] END max_depth=None, max_features=8, min_samples_split=20, n_estimators=1000; total time=  13.4s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=1000; total time=   4.6s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=1000; total time=   4.2s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=1000; total time=   4.1s
[CV] END max_depth=10, max_features=auto, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=20, n_estimators=1000; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=20, n_estimators=1000; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=20, n_estimators=1000; total time=   0.0s
[CV] END max_depth=5, max_features=8, min_samples_split=15, n_estimators=200; total time=   1.1s
[CV] END max_depth=5, max_features=8, min_samples_split=15, n_estimators=200; total time=   1.1s
[CV] END max_depth=5, max_features=8, min_samples_split=15, n_estimators=200; total time=   1.0s
[CV] END max_depth=10, max_features=7, min_samples_split=20, n_estimators=500; total time=   4.2s
[CV] END max_depth=10, max_features=7, min_samples_split=20, n_estimators=500; total time=   4.1s
[CV] END max_depth=10, max_features=7, min_samples_split=20, n_estimators=500; total time=   4.2s
[CV] END max_depth=None, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=8, max_features=8, min_samples_split=2, n_estimators=500; total time=   4.1s
[CV] END max_depth=8, max_features=8, min_samples_split=2, n_estimators=500; total time=   4.3s
[CV] END max_depth=8, max_features=8, min_samples_split=2, n_estimators=500; total time=   4.1s

In [33]:
models={
    "RandomForestRegressor":RandomForestRegressor(n_estimators=500, min_samples_split= 2, max_features= 5, max_depth=None),
    "KNeighborsRegressor":KNeighborsRegressor(n_neighbors=10)
}

In [34]:
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)

    y_train_pred=model.predict(X_train)
    y_test_pred=model.predict(X_test)

    model_train_mae,model_train_mse,model_train_rmse,model_train_r2_sc=evaluate_model(y_train,y_train_pred)
    model_test_mae,model_test_mse,model_test_rmse,model_test_r2_sc=evaluate_model(y_test,y_test_pred)

    print(list(models.keys())[i])

    print("Model train Performance")
    print('mean_absolute_error:{:.4f}'.format(model_train_mae))
    print('mean_square_error:{:.4f}'.format(model_train_mse))
    print('root_mean_square_error:{:.4f}'.format(model_train_rmse))
    print('r2_score:{:.4f}'.format(model_train_r2_sc))
    print("---")
    print("Model test Performance")
    print('mean_absolute_error:{:.4f}'.format(model_test_mae))
    print('mean_square_error:{:.4f}'.format(model_test_mse))
    print('root_mean_square_error:{:.4f}'.format(model_test_rmse))
    print('r2_score:{:.4f}'.format(model_test_r2_sc))

    print("="*32)
    print(" ")

RandomForestRegressor
Model train Performance
mean_absolute_error:38974.0737
mean_square_error:16622757137.8941
root_mean_square_error:128929.2718
r2_score:0.9795
---
Model test Performance
mean_absolute_error:97763.9991
mean_square_error:42620110036.2962
root_mean_square_error:206446.3854
r2_score:0.9434
================================

KNeighborsRegressor
Model train Performance
mean_absolute_error:103471.6175
mean_square_error:132103680886.5996
root_mean_square_error:363460.7006
r2_score:0.8371
---
Model test Performance
mean_absolute_error:117487.1310
mean_square_error:69633846174.3837
root_mean_square_error:263882.2582
r2_score:0.9075
================================

In [35]:
pwd

'c:\\Users\\phani\\OneDrive\\Desktop\\Geetha\\Learnings\\GENAI\\ML\\RandomForest'